### ISSUE TITLE
Regression in 1.1.0

### ISSUE THREAD

**Issue by vladikoff** [stevemao/git-semver-tags#3] opened 2015-12-30 16:55 UTC
### STR

```
sudo npm i -g ajoslin/conventional-changelog
git clone git@github.com:mozilla/fxa-auth-server.git
conventional-changelog 
```
#### OUTPUT:

```
TypeError: Error in conventional-changelog-writer: Cannot read property '0' of undefined
```
### Details

I locked the version to 1.0.0, see https://github.com/vladikoff/conventional-changelog/commit/5844989cb291be8f97a0b798f13216c3140377b4#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L35. Now it works fine again.

```
sudo npm i -g vladikoff/conventional-changelog#fix-semvertags 
conventional-changelog 
```
#### OUTPUT:

```
➜  fxa-auth-server git:(master) conventional-changelog 
<a name="1.51.1"></a>
## 1.51.1 (2015-12-30)


### chore

* chore(docs): remove misleading references to awsbox ([b77c58c](https://github.com/mozilla/fxa-auth-server/commit/b77c58c))

### docs

* docs(profile): document the /account/profile endpoint ([990b1ef](https://github.com/mozilla/fxa-auth-server/commit/990b1ef)), closes [#1128](https://github.com/mozilla/fxa-auth-server/issues/1128)

### fix

* fix(log): add mozlog fmt properly ([35d8291](https://github.com/mozilla/fxa-auth-server/commit/35d8291)), closes [#1138](https://github.com/mozilla/fxa-auth-server/issues/1138)

* Merge pull request #1137 from mozilla/1128-document-profile-endpoint ([c665cc9](https://github.com/mozilla/fxa-auth-server/commit/c665cc9))
* Merge pull request #1142 from jrgm/chore-remove-misleading-references-to-awsbox ([07e77ae](https://github.com/mozilla/fxa-auth-server/commit/07e77ae))
* Merge pull request #1143 from mozilla/i1138 ([726351e](https://github.com/mozilla/fxa-auth-server/commit/726351e))
```

Ref https://github.com/ajoslin/conventional-changelog/issues/130

`gitSemverTags` is now reporting undefined since 1.1.0:
![](http://v14d.com/i/56840c5295884.jpg)

**Comment by vladikoff** [comment] 2015-12-30 16:55
Could you revert 1.1.0 or what's the best plan here?

**Comment by stevemao** [comment] 2015-12-30 22:01
:open_mouth: 1.0.0 fails some edge case tests. I'll have to have a look. What's your git version? Tests passed on CI and my local machine.

**Comment by vladikoff** [comment] 2015-12-30 22:03
I'm on `git version 2.5.4 (Apple Git-61)`

**Comment by stevemao** [comment] 2015-12-30 22:03
Just out of interest your screenshot is webstorm debugger?

**Comment by vladikoff** [comment] 2015-12-30 22:04
> Just out of interest your screenshot is webstorm debugger?

Yeah, I had to tweak the code a bit to have it catch the error properly, but should be okay for breakpoints either way.

**Comment by NicBright** [comment] 2015-12-31 12:17
Hello there,

I've experienced the same issue today and managed to track it down to this issue, too. 

The problem is the size of the output.

[Here](https://github.com/stevemao/git-semver-tags/commit/9dfeaa56fddafaea5a98b33fe2ddc8a7fd038afe) you've changed the underlying git command. If I run the previous command `'git log --tags --simplify-by-decoration --pretty=format:"%d"'` the size (for my git repository) is only about 170 bytes.
However, running the new command `git log --decorate` the output size is about 1.6M.

And that's the problem: because Node's child_process.exec() command by default has its `maxBuffer` option set to be "only" 200K.

I see three possible solutions to fix this regression:
A) add a generous maxBuffer option to the `exec()` call in [git-semver-tags](https://github.com/stevemao/git-semver-tags/blob/master/index.js#L8) (maybe 100M?) or
B) instead of calling exec(), use spawn() and streaming
C) change the `git` command to produce a smaller output. Maybe a simple `git tag` will do?

Regards,
Nicolas

**Comment by stevemao** [comment] 2015-12-31 12:26
Thanks @NicBright , it helps a lot :)

**Comment by stevemao** [comment] 2015-12-31 12:26
How'd you know the size of the out put :)

**Comment by stevemao** [comment] 2015-12-31 12:28
I always wanted to simplify the git command but with no success. PR welcome to change it. #1

**Comment by NicBright** [comment] 2015-12-31 12:51
> How'd you know the size of the out put :)

I just ran the command in a console, dumping the output in a file ("git log (...) > dump.txt") and then having a look at the file size :-)

**Comment by stevemao** [comment] 2015-12-31 22:47
Thanks for having a look at this @NicBright , hope it's fixed now.

**Closed as completed** 2015-12-31 22:46 UTC

**Comment by vladikoff** [comment] 2015-12-31 22:51
Works here! Thanks @stevemao !

**Comment by stevemao** [comment] 2015-12-31 22:52
Cool, good to know @vladikoff :)
